# Generated by Django 4.1.3 on 2023-02-22 11:52

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to=core.helpers.PathAndRename("documents/")
                    ),
                ),
                ("INN", models.CharField(max_length=14, null=True)),
                ("short_name", models.CharField(max_length=30, null=True)),
                ("full_name", models.CharField(max_length=200, null=True)),
                (
                    "registration_form",
                    models.CharField(
                        choices=[
                            ("with_nds", "with NDS"),
                            ("without_nds", "without NDS"),
                        ],
                        default="with_nds",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("address", models.CharField(max_length=255, null=True)),
                ("owner", models.CharField(max_length=100, null=True)),
                ("bank_account", models.CharField(max_length=16, null=True)),
                ("bik", models.CharField(max_length=9, null=True)),
                ("shop_name", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("moderation", "moderation"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="moderation",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(max_length=1500, null=True)),
            ],
        ),
    ]
