# Generated by Django 4.1.3 on 2023-02-22 11:52

import autoslug.fields
import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageCategory",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="title",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("support_email", models.EmailField(max_length=254, null=True)),
                (
                    "header_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "footer_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=155, null=True)),
                ("facebook", models.CharField(blank=True, max_length=100, null=True)),
                ("twitter", models.CharField(blank=True, max_length=100, null=True)),
                ("youtube", models.CharField(blank=True, max_length=100, null=True)),
                ("gmail", models.CharField(blank=True, max_length=100, null=True)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("map", models.TextField(blank=True, max_length=2000, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.helpers.PathAndRename("site_settings/logos/"),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("content", models.JSONField(db_index=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, db_index=True, null=True, upload_to="post_images"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="pages.pagecategory",
                    ),
                ),
            ],
        ),
    ]
