# Generated by Django 4.1.3 on 2023-02-22 11:52

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Social Network"),
                ),
                (
                    "link",
                    models.CharField(
                        max_length=255, verbose_name="Social Network Link"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Shop's id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Shop's name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Shop's slug",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Shop's email"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Shop's address"),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, verbose_name="Is shop verified?"
                    ),
                ),
                ("phone", models.CharField(max_length=100, unique=True)),
                (
                    "cover_picture",
                    models.ImageField(
                        upload_to=core.helpers.PathAndRename("shop/covers/"),
                        verbose_name="Shop's cover picture",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        upload_to=core.helpers.PathAndRename("shop/profiles/"),
                        verbose_name="Shop's profile picture",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
