# Generated by Django 4.1.3 on 2023-02-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Attribute name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product attribute",
                "verbose_name_plural": "Product attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=100, verbose_name="Attribute value"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="attributes.attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product attribute value",
                "verbose_name_plural": "Product attribute values",
                "ordering": ["value"],
            },
        ),
    ]
